### ISSUE TITLE
Unable to open .sif file

### ISSUE THREAD

**Issue by arteys** [fujiisoup/sif_parser#27]
Hi. I can't open a file containing microscopic images. Is this a problem with the file or am I doing something wrong?

`Traceback (most recent call last):
  File "C:\Users\Modern\AppData\Local\Programs\Python\Python310\lib\site-packages\sif_parser\sif_open.py", line 12, in np_open
    tile, size, no_images, info = _open(f)
  File "C:\Users\Modern\AppData\Local\Programs\Python\Python310\lib\site-packages\sif_parser\_sif_open.py", line 59, in _open
    if _to_string(fp.read(36)) != _MAGIC:
AttributeError: 'str' object has no attribute 'read'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Modern\Desktop\Python\Py_sif_reader.py\import sif_parser.py", line 7, in <module>
    data, info = sif_parser.utils.parse('./test.sif')
  File "C:\Users\Modern\AppData\Local\Programs\Python\Python310\lib\site-packages\sif_parser\utils.py", line 52, in parse
    data, info = sif.np_open(file)
  File "C:\Users\Modern\AppData\Local\Programs\Python\Python310\lib\site-packages\sif_parser\sif_open.py", line 15, in np_open
    tile, size, no_images, info = _open(f)
  File "C:\Users\Modern\AppData\Local\Programs\Python\Python310\lib\site-packages\sif_parser\_sif_open.py", line 164, in _open
    info['FrameAxis'] = _read_string(fp) # Line 26 or 39
  File "C:\Users\Modern\AppData\Local\Programs\Python\Python310\lib\site-packages\sif_parser\_sif_open.py", line 18, in _read_string
    length = int(_to_string(fp.readline()))
ValueError: invalid literal for int() with base 10: '17 Spectrograph_None\n'`

[test.zip](https://github.com/fujiisoup/sif_parser/files/13537000/test.zip)

**Comment by fujiisoup** [comment]
Thank you for raising the issue. I can reproduce this problem. I will work for this.
